// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUZxH-N5tz_sktA78PnR7WKLJhF-nsY6Y',
    appId: '1:645882945987:web:c2dd1a9042c2f336939d76',
    messagingSenderId: '645882945987',
    projectId: 'collab-shopping-list-app',
    authDomain: 'collab-shopping-list-app.firebaseapp.com',
    storageBucket: 'collab-shopping-list-app.firebasestorage.app',
    measurementId: 'G-0SPSGW8HTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrEUkgxwwyQ6lr6QXQXfo0Nu8S3pfzcWQ',
    appId: '1:645882945987:android:7ebfb11e6ccbfb14939d76',
    messagingSenderId: '645882945987',
    projectId: 'collab-shopping-list-app',
    storageBucket: 'collab-shopping-list-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzCEeI7dZhpkFDyfYWZsiIkYLAZPF4itk',
    appId: '1:645882945987:ios:6b7e17bde24b01a8939d76',
    messagingSenderId: '645882945987',
    projectId: 'collab-shopping-list-app',
    storageBucket: 'collab-shopping-list-app.firebasestorage.app',
    iosBundleId: 'com.example.collaborativeshoppinglistapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzCEeI7dZhpkFDyfYWZsiIkYLAZPF4itk',
    appId: '1:645882945987:ios:6b7e17bde24b01a8939d76',
    messagingSenderId: '645882945987',
    projectId: 'collab-shopping-list-app',
    storageBucket: 'collab-shopping-list-app.firebasestorage.app',
    iosBundleId: 'com.example.collaborativeshoppinglistapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUZxH-N5tz_sktA78PnR7WKLJhF-nsY6Y',
    appId: '1:645882945987:web:c6fa11fc1bba6dcb939d76',
    messagingSenderId: '645882945987',
    projectId: 'collab-shopping-list-app',
    authDomain: 'collab-shopping-list-app.firebaseapp.com',
    storageBucket: 'collab-shopping-list-app.firebasestorage.app',
    measurementId: 'G-Q1L8SNC4PD',
  );
}
